name: Deploy to Server

on:
  push:
    branches:
      - main
      - homologacao

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .env file
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "${{ secrets.ENV_PRD }}" > .env
          elif [ "${{ github.ref }}" = "refs/heads/homologacao" ]; then
            echo "${{ secrets.ENV_HML }}" > .env
          fi

      - name: Show env (teste)
        run: cat .env

      - name: Add known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/project/integracao-pix
            git pull origin main
