name: Deploy to Server

on:
  push:
    branches:
      - main
      - homologacao

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Server (Laravel com .env temporário)
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/project/integracao-pix
            git pull origin ${{ github.ref_name }}

            # Definir caminho do container (substitua pelo nome correto)
            CONTAINER_NAME=laravel_app

            # Criar .env dentro do container
            if [ "${{ github.ref_name }}" = "main" ]; then
              sudo docker exec $CONTAINER_NAME sh -c "echo '${{ secrets.ENV_PRD }}' > .env"
            elif [ "${{ github.ref_name }}" = "homologacao" ]; then
              sudo docker exec $CONTAINER_NAME sh -c "echo '${{ secrets.ENV_HML }}' > .env"
            fi

            # Rodar artisan dentro do container
            sudo docker exec $CONTAINER_NAME php artisan config:clear
            sudo docker exec $CONTAINER_NAME php artisan config:cache

            # Apagar o .env dentro do container
            sudo docker exec $CONTAINER_NAME rm .env

            echo "✅ Deploy finalizado com .env temporário dentro do container"
